import React from "react";

const SvgCircles = () => {
  return (
    <svg
      id="Layer_2"
      data-name="Layer 2"
      xmlns="http://www.w3.org/2000/svg"
      xlink="http://www.w3.org/1999/xlink"
      viewBox="0 0 1748.81 1187.47"
    >
      <g id="Layer_1-2" data-name="Layer 1">
        <g className="cls-269">
          <g>
            <g>
              <rect
                id="shamasi"
                className="cls-rect"
                x="1159.56"
                y="738.61"
                width="48.7"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="la baia"
                className="cls-rect"
                x="1205.12"
                y="712.9"
                width="48.7"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="norodilcazar"
                className="cls-rect"
                x="1418.67"
                y="612"
                width="75.33"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="seashell"
                className="cls-rect"
                x="1119.89"
                y="686.03"
                width="48.61"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="amwaj"
                className="cls-rect"
                x="1109.92"
                y="865.49"
                width="38.27"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="bianchi"
                className="cls-rect"
                x="1144.42"
                y="897.66"
                width="41.49"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="telal"
                className="cls-rect"
                x="1073.37"
                y="848.15"
                width="36.4"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="lavistabay"
                className="cls-rect"
                x="955.99"
                y="677.59"
                width="59.16"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="waterway"
                className="cls-rect"
                x="915.67"
                y="613.91"
                width="55.35"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="dose"
                className="cls-rect"
                x="905.3"
                y="769.63"
                width="36.4"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="lvls"
                className="cls-rect"
                x="884.77"
                y="814.94"
                width="36.4"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="jefaira"
                className="cls-rect"
                x="738.97"
                y="782.57"
                width="47.83"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="themed"
                className="cls-rect"
                x="643.41"
                y="552.15"
                width="44.33"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="zoya"
                className="cls-rect"
                x="1058.26"
                y="674.86"
                width="32.72"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="mazzarine"
                className="cls-rect"
                x="1482.83"
                y="764.66"
                width="58.49"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="seazen"
                className="cls-rect"
                x="942.19"
                y="830.74"
                width="40.81"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="salt"
                className="cls-rect"
                x="791.82"
                y="811.92"
                width="36.4"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="seaview"
                className="cls-rect"
                x="756.36"
                y="625.19"
                width="55.64"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="calicoast"
                className="cls-rect"
                x="675.02"
                y="594.4"
                width="53.38"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="seashore"
                className="cls-rect"
                x="290.13"
                y="687.44"
                width="51.58"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="remal"
                className="cls-rect"
                x="395.13"
                y="733.22"
                width="36.32"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="summer"
                className="cls-rect"
                x="130.86"
                y="543.01"
                width="44.48"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="palmhills247"
                className="cls-rect"
                x="90.38"
                y="685.33"
                width="52.31"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="almazabay"
                className="cls-rect"
                x="24.61"
                y="777.47"
                width="62.21"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="azha"
                className="cls-rect"
                x="271.1"
                y="480.18"
                width="36.32"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="ramla"
                className="cls-rect"
                x="240.94"
                y="794.21"
                width="38.83"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="masayf"
                className="cls-rect"
                x="305.5"
                y="518.14"
                width="57.33"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="alura"
                className="cls-rect"
                x="1240.99"
                y="889.32"
                width="37.49"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="playa"
                className="cls-rect"
                x="1033.02"
                y="871.26"
                width="36.4"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="dbay"
                className="cls-rect"
                x="1007.01"
                y="652.25"
                width="36.4"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="haceindawest"
                className="cls-rect"
                x="433.65"
                y="576.54"
                width="77.79"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="naiabay"
                className="cls-rect"
                x="338.4"
                y="777.32"
                width="46.66"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <g>
                <rect
                  id="whiteSands"
                  className="cls-rect"
                  x="1652.31"
                  y="508.92"
                  width="70.88"
                  height="11.11"
                />
              </g>
            </g>
          </g>
          <g>
            <g>
              <rect
                id="marina2"
                className="cls-rect"
                x="1630.5"
                y="543.93"
                width="47.88"
                height="11.11"
              />
            </g>
          </g>

          <g></g>
          <g>
            <g>
              <g>
                <rect
                  id="eko"
                  className="cls-rect"
                  x="1627.18"
                  y="688.7"
                  width="87.06"
                  height="11.11"
                />
              </g>
            </g>
          </g>
          <g>
            <g>
              <g>
                <rect
                  id="marina8"
                  className="cls-rect"
                  x="1598.2"
                  y="582.72"
                  width="47.89"
                  height="11.11"
                />
              </g>
            </g>
          </g>
          <g>
            <g>
              <rect
                id="winterngd"
                className="cls-rect"
                x="1548.91"
                y="555.07"
                width="61.43"
                height="11.11"
              />
            </g>
          </g>
          <g></g>
          <g>
            <g>
              <rect
                id="solycoast"
                className="cls-rect"
                x="1611.17"
                y="760.36"
                width="57.32"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="marina3"
                className="cls-rect"
                x="1578.11"
                y="720.74"
                width="47.27"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="palmhills"
                className="cls-rect"
                x="1448.57"
                y="817.89"
                width="55.01"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="latini"
                className="cls-rect"
                x="1502.43"
                y="580.61"
                width="51.66"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="portogolf"
                className="cls-rect"
                x="1527.16"
                y="745.34"
                width="58.45"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="downtown"
                className="cls-rect"
                x="1461.88"
                y="644.01"
                width="62.09"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="massaya"
                className="cls-rect"
                x="1177.55"
                y="868.07"
                width="61.43"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="alma"
                className="cls-rect"
                x="1423.07"
                y="871.52"
                width="31.02"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="zahra"
                className="cls-rect"
                x="1377.98"
                y="826.99"
                width="36.4"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="soul"
                className="cls-rect"
                x="815.87"
                y="565.31"
                width="36.4"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="haceindabay"
                className="cls-rect"
                x="1336.09"
                y="647.26"
                width="69.1"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="qnorth"
                className="cls-rect"
                x="1277.42"
                y="844.3"
                width="43.08"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="marassi"
                className="cls-rect"
                x="1293.92"
                y="660.62"
                width="45.82"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="mountainview"
                className="cls-rect"
                x="1378.59"
                y="674.1"
                width="79.19"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="mountainview"
                className="cls-rect"
                x="568.23"
                y="768.03"
                width="79.19"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="lavistacascada"
                className="cls-rect"
                x="1311.74"
                y="887.22"
                width="79.48"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="stellaheights"
                className="cls-rect"
                x="1245.4"
                y="692.33"
                width="77.29"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="haciendaredwhite"
                className="cls-rect"
                x="1068.27"
                y="717.14"
                width="102.47"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="lasirena"
                className="cls-rect"
                x="977"
                y="854.44"
                width="62.09"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="katameyacoast"
                className="cls-rect"
                x="832.53"
                y="650.27"
                width="83.78"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <g>
                <rect
                  id="gaja"
                  className="cls-rect"
                  x="664.7"
                  y="797.37"
                  width="44.33"
                  height="11.11"
                />
              </g>
            </g>
          </g>

          <g>
            <g>
              <rect
                id="azzarisland"
                className="cls-rect"
                x="820.2"
                y="761.51"
                width="69.43"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="directionwhite"
                className="cls-rect"
                x="698.1"
                y="551.54"
                width="81.87"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="junesodic"
                className="cls-rect"
                x="689.62"
                y="727.15"
                width="62.68"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <g>
                <rect
                  id="swanlake"
                  className="cls-rect"
                  x="624.67"
                  y="737.83"
                  width="54.01"
                  height="11.11"
                />
              </g>
            </g>
          </g>
          <g>
            <g>
              <g>
                <rect
                  id="solare"
                  className="cls-rect"
                  x="610.86"
                  y="614.1"
                  width="40.66"
                  height="11.11"
                />
              </g>
            </g>
          </g>

          <g>
            <g>
              <rect
                id="lyvgates"
                className="cls-rect"
                x="557.09"
                y="574.24"
                width="55.38"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="caesarsodic"
                className="cls-rect"
                x="527.05"
                y="730.32"
                width="67.94"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="koun"
                className="cls-rect"
                x="512.92"
                y="601.12"
                width="31.97"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="marselia5"
                className="cls-rect"
                x="417.25"
                y="807.45"
                width="66.22"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="elabdresort"
                className="cls-rect"
                x="187.76"
                y="565.18"
                width="75.32"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="silversand"
                className="cls-rect"
                x="52.6"
                y="539.37"
                width="66.28"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="lavistabayraselhekma"
                className="cls-rect"
                x="470.86"
                y="772.75"
                width="59.16"
                height="11.11"
              />
            </g>
          </g>
          <g>
            <g>
              <rect
                id="foukabay"
                className="cls-rect"
                x="362.23"
                y="598.77"
                width="57.33"
                height="11.11"
              />
            </g>
          </g>

          <g>
            <g>
              <rect
                id="cecilalagoons"
                className="cls-rect"
                x="140.97"
                y="719.39"
                width="83.47"
                height="11.11"
              />
            </g>
          </g>
        </g>
      </g>
    </svg>
  );
};

export default SvgCircles;
